project_id = "lheriwtyqgkodzdgrtit"

[functions.explain-topic]
verify_jwt = false

[functions.generate-timetable]
verify_jwt = false

[functions.generate-study-guide]
verify_jwt = false

[functions.parse-curriculum]
verify_jwt = false

[functions.save-curriculum]
verify_jwt = false

[functions.ai-research-agent]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false

[functions.research-chat]
verify_jwt = false