import html2pdf from "html2pdf.js";
import MarkdownIt from "markdown-it";

type Msg = { role: "user" | "assistant"; content: string };

export async function exportChatToPdf(messages: Msg[], title?: string) {
  const md = new MarkdownIt({ html: true });

  const chatHtml = messages
    .map((m) => {
      const label = m.role === "user" ? "You" : "Research Assistant";
      const bgColor = m.role === "user" ? "#e8f0fe" : "#f8f9fa";
      const borderColor = m.role === "user" ? "#4285f4" : "#34a853";
      const content =
        m.role === "user"
          ? `<p style="white-space:pre-wrap;margin:0">${m.content.replace(/</g, "&lt;")}</p>`
          : md.render(m.content);

      return `
        <div style="margin-bottom:16px;padding:14px 18px;background:${bgColor};border-left:4px solid ${borderColor};border-radius:8px;">
          <div style="font-weight:700;font-size:11px;text-transform:uppercase;letter-spacing:0.5px;color:${borderColor};margin-bottom:8px;">${label}</div>
          <div style="font-size:13px;line-height:1.7;color:#1a1a1a">${content}</div>
        </div>`;
    })
    .join("");

  const wrapper = document.createElement("div");
  wrapper.innerHTML = `
    <div style="font-family:'Segoe UI',system-ui,sans-serif;padding:0;color:#1a1a1a">
      <div style="text-align:center;margin-bottom:24px;padding-bottom:16px;border-bottom:2px solid #4285f4">
        <h1 style="font-size:20px;margin:0 0 4px">Bookpadi Research Assistant</h1>
        <p style="font-size:11px;color:#666;margin:0">${title || "Research Conversation"} · ${new Date().toLocaleDateString("en-NG", { year: "numeric", month: "long", day: "numeric" })}</p>
      </div>
      ${chatHtml}
      <div style="text-align:center;font-size:9px;color:#999;margin-top:24px;padding-top:12px;border-top:1px solid #e0e0e0">
        Generated by Bookpadi Research Assistant
      </div>
    </div>`;

  const opt = {
    margin: [12, 14, 12, 14] as [number, number, number, number],
    filename: `research-${Date.now()}.pdf`,
    image: { type: "jpeg", quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: "mm", format: "a4", orientation: "portrait" as const },
  };

  await html2pdf().set(opt).from(wrapper).save();
}
